/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://tzh4btvj2bf6dgh2c546reboqa.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "Auth": {
        "region": "ap-northeast-1",
        "userPoolId": "ap-northeast-1_q9iunJy7n",
        "userPoolWebClientId": "5c8ui5tifprn486s06tuh8r882",
        "identityPoolId": "ap-northeast-1:49af8eca-59ed-4aea-abce-d4bd9335335d"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "filestoragestack-s3bucket64cb25af-15549unt3ucbg",
            "region": "ap-northeast-1"
        }
    }
};


export default awsmobile;
